import { defineConfig } from 'vitest/config';

export default defineConfig({
  test: {
    globals: true,
    environment: 'node',
    include: [
      'tests/unit/browserProofContract.test.js',
      'tests/unit/browserSnapshotLifecycle.test.js',
      'tests/unit/browserTransactionContract.test.js',
      'tests/unit/browserTransactionController.test.js',
      'tests/unit/browserTransactionEventJournal.test.js',
      'tests/unit/browserTransactionRuntime.test.js',
      'tests/unit/browserTransactionStateMachine.test.js',
      'tests/unit/conductorRunnerImmutableAuthority.test.js',
      'tests/unit/conductorStaticRuntime.test.js',
      'tests/unit/controllerConductorOutcomeMapping.test.js',
      'tests/unit/controllerActionExecutionGateway.test.js',
      'tests/unit/controllerBrowserMutationTaxonomy.test.js',
      'tests/unit/controllerCompositeProtocols.test.js',
      'tests/unit/controllerCompositeExecutor.test.js',
      'tests/unit/controllerEvidenceReader.test.js',
      'tests/unit/controllerExecutionScheduler.test.js',
      'tests/unit/controllerFailureAttribution.test.js',
      'tests/unit/controllerMcpFillAcknowledgment.test.js',
      'tests/unit/controllerMcpNextControl.test.js',
      'tests/unit/controllerMcpOptionalConditions.test.js',
      'tests/unit/controllerMcpSemanticRanking.test.js',
      'tests/unit/controllerRecoveryDirectives.test.js',
      'tests/unit/controllerRecoveryCoordinator.test.js',
      'tests/unit/controllerRecoveryProposals.test.js',
      'tests/unit/controllerResumeReconciler.test.js',
      'tests/unit/controllerSemanticResolver.test.js',
      'tests/unit/controllerTypedAdapterRegistry.test.js',
      'tests/unit/controllerVerdictProjector.test.js',
      'tests/unit/operationContractV2.test.js',
      'tests/unit/semanticSelectionState.test.js',
      'tests/unit/semanticTextInputState.test.js',
      'tests/unit/semanticTemporalSelection.test.js',
    ],
    pool: 'forks',
    maxWorkers: 1,
    minWorkers: 1,
    fileParallelism: false,
    testTimeout: 10_000,
    hookTimeout: 10_000,
    teardownTimeout: 3_000,
  },
});
