'use strict';

/**
 * Lint gates for generated Playwright spec code.
 *
 * Two engines run together:
 *   1. The regex rules defined in this file — string-pattern checks for
 *      banned APIs, leaked credentials, hardcoded URLs, etc. Calibrated
 *      for Playwright TS test files generated by Claude.
 *   2. The AST engine in `server/lib/specAst.js` (Phase E6) — scope-aware
 *      checks that need to know which `expect(...)` belongs to which
 *      `test(...)`, whether a `page.click()` is awaited, etc.
 *
 * Findings from both are merged into a single array. If the AST engine's
 * parser chokes on malformed/partial code, its findings list is empty and
 * the regex engine still contributes its findings — graceful fallback.
 *
 * Each finding: { rule, severity ('error'|'warning'), line, message,
 * snippet?, engine? }. `engine` is 'ast' for AST findings; regex findings
 * omit it. lintPassed === true iff no `error`-severity findings (from
 * either engine).
 */

const specAst = require('../lib/specAst');

const RULES = [
  // ── Imports & frame ──────────────────────────────────────
  {
    id: 'requires-playwright-import',
    severity: 'error',
    test(lines, joined) {
      return /from\s+['"]@playwright\/test['"]/.test(joined)
        ? null
        : {
            line: 1,
            message: 'Missing `import { test, expect } from "@playwright/test"`',
          };
    },
  },
  {
    id: 'has-test-block',
    severity: 'error',
    test(lines, joined) {
      return /\btest\s*\(/.test(joined) || /\btest\.describe\s*\(/.test(joined)
        ? null
        : { line: 1, message: 'No test() or test.describe() block found' };
    },
  },

  // ── Banned APIs (anti-patterns) ──────────────────────────
  {
    id: 'no-waitForTimeout',
    severity: 'error',
    line(lines) {
      return findLine(lines, /\.\s*waitForTimeout\s*\(/);
    },
    message:
      'page.waitForTimeout() is forbidden — use locator.waitFor / expect.toBeVisible({timeout}) instead.',
  },
  {
    id: 'no-console-log',
    severity: 'warning',
    line(lines) {
      return findLine(lines, /\bconsole\.(log|debug|info)\s*\(/);
    },
    message: 'console.log/debug/info should not ship in suite code.',
  },
  {
    id: 'no-debugger',
    severity: 'error',
    line(lines) {
      return findLine(lines, /\bdebugger\b/);
    },
    message: 'debugger statement must be removed before submission.',
  },
  {
    id: 'no-only-or-skip',
    severity: 'error',
    line(lines) {
      return findLine(lines, /\b(test|describe)\.(only|skip)\s*\(/);
    },
    message:
      'test.only() / test.skip() / describe.only() must not be committed — they break parallel runs.',
  },
  {
    id: 'no-fixme-todo',
    severity: 'warning',
    line(lines) {
      return findLine(lines, /\b(TODO|FIXME|XXX)\b/);
    },
    message: 'TODO/FIXME comment present.',
  },

  // ── Locator hygiene ──────────────────────────────────────
  {
    id: 'no-css-id-selector-chain',
    severity: 'warning',
    line(lines) {
      // Locators like 'div > .foo > #bar' or '#root > div > div' — brittle.
      return findLine(
        lines,
        /(?:page\.locator|page\.\$x?|page\.\$)\(\s*['"`][^'"`]*[>\s]\s*#[a-zA-Z][\w-]*[^'"`]*['"`]/
      );
    },
    message: 'Brittle compound CSS selector — prefer getByRole / getByTestId.',
  },
  {
    id: 'no-nth-child-locator',
    severity: 'warning',
    line(lines) {
      return findLine(lines, /:nth-(?:child|of-type)\s*\(/);
    },
    message: ':nth-child / :nth-of-type is fragile — prefer named locators.',
  },
  {
    id: 'no-xpath',
    severity: 'warning',
    line(lines) {
      return findLine(lines, /['"`]xpath=|['"`]\/\/[a-z]/i);
    },
    message: 'XPath locator detected — prefer getByRole / getByTestId.',
  },

  // ── Credential & secret hygiene ──────────────────────────
  {
    id: 'leaked-credential',
    severity: 'error',
    customScan(lines) {
      const out = [];
      const patterns = [
        // password: 'foo'   OR   password = 'foo'   (skip env / process.env)
        /\b(password|passwd|pwd|secret|api[_-]?key|token)\s*[:=]\s*['"`]([^'"`]{4,})['"`]/i,
        // Authorization: 'Bearer abc...' literal
        /Authorization\s*:\s*['"`]Bearer\s+[a-zA-Z0-9._-]+['"`]/,
        // sk-ant-... key literal
        /['"`](sk-ant-[a-zA-Z0-9_-]{20,})['"`]/,
        // Generic 32+ char hex secret literal
        /['"`]([a-f0-9]{32,})['"`]/i,
      ];
      lines.forEach((raw, i) => {
        // skip comments
        if (/^\s*(\/\/|\*|\/\*)/.test(raw)) return;
        // skip env access
        if (/process\.env\./.test(raw)) return;
        for (const p of patterns) {
          const m = raw.match(p);
          if (m) {
            out.push({
              line: i + 1,
              message: `Possible secret literal in source (matched ${m[0].slice(0, 40)}…). Use process.env or test fixtures.`,
              snippet: raw.trim().slice(0, 120),
            });
            break;
          }
        }
      });
      return out;
    },
  },

  // ── Network / config hygiene ─────────────────────────────
  {
    id: 'no-hardcoded-localhost',
    severity: 'warning',
    line(lines) {
      return findLine(lines, /['"`]https?:\/\/(?:localhost|127\.0\.0\.1)(?::\d+)?[^'"`]*['"`]/);
    },
    message: 'Hardcoded localhost URL — use baseURL / process.env.',
  },
  {
    id: 'no-disabled-ssl',
    severity: 'error',
    line(lines) {
      return findLine(lines, /ignoreHTTPSErrors\s*:\s*true|rejectUnauthorized\s*:\s*false/);
    },
    message: 'Disabling TLS verification is not allowed in committed tests.',
  },

  // ── Assertion hygiene ────────────────────────────────────
  {
    id: 'has-at-least-one-expect',
    severity: 'error',
    test(lines, joined) {
      return /\bexpect\s*\(/.test(joined)
        ? null
        : { line: 1, message: 'Spec contains no expect() assertion.' };
    },
  },
];

function findLine(lines, re) {
  for (let i = 0; i < lines.length; i++) {
    const raw = lines[i];
    if (/^\s*(\/\/|\*)/.test(raw)) continue; // skip comments
    if (re.test(raw)) {
      return { line: i + 1, snippet: raw.trim().slice(0, 120) };
    }
  }
  return null;
}

/**
 * Run all rules against `code` and return findings + lintPassed.
 * @param {string} code
 * @returns {{ lintPassed: boolean, findings: Array, errorCount: number, warningCount: number }}
 */
function lint(code) {
  if (typeof code !== 'string' || code.length === 0) {
    return {
      lintPassed: false,
      findings: [{ rule: 'no-code', severity: 'error', line: 1, message: 'No spec code to lint.' }],
      errorCount: 1,
      warningCount: 0,
    };
  }

  const lines = code.split(/\r?\n/);
  const joined = code;
  const findings = [];

  for (const r of RULES) {
    if (r.customScan) {
      const hits = r.customScan(lines);
      for (const h of hits) {
        findings.push({ rule: r.id, severity: r.severity, ...h });
      }
      continue;
    }
    if (r.line) {
      const hit = r.line(lines);
      if (hit) {
        findings.push({
          rule: r.id,
          severity: r.severity,
          line: hit.line,
          message: r.message,
          snippet: hit.snippet,
        });
      }
      continue;
    }
    if (r.test) {
      const hit = r.test(lines, joined);
      if (hit) {
        findings.push({
          rule: r.id,
          severity: r.severity,
          line: hit.line || 1,
          message: hit.message,
        });
      }
    }
  }

  // Phase E6 — merge AST-engine findings. The AST engine's scope-aware
  // rules (per-test expect, missing-await on locator, etc.) extend what
  // the regex engine can see without overlapping with it. A parse error
  // from @babel/parser returns an empty findings list and a non-null
  // `parseError`; we don't surface the parser failure as a lint finding
  // because malformed code already trips the regex rules on its own.
  const astResult = specAst.lintAst(code);
  if (Array.isArray(astResult?.findings) && astResult.findings.length) {
    for (const f of astResult.findings) findings.push(f);
  }

  const errorCount = findings.filter((f) => f.severity === 'error').length;
  const warningCount = findings.filter((f) => f.severity === 'warning').length;
  return {
    lintPassed: errorCount === 0,
    findings,
    errorCount,
    warningCount,
    astParseError: astResult?.parseError || null,
  };
}

module.exports = { lint, RULES };
