'use strict';

/**
 * Browser-context configuration for the @playwright/mcp subprocess
 * (Phase E10.5).
 *
 * @playwright/mcp accepts most browser-context flags via its CLI:
 *   --viewport-size, --device, --user-agent, --grant-permissions,
 *   --ignore-https-errors, --proxy-server, --proxy-bypass, --init-script,
 *   --output-dir, --test-id-attribute.
 *
 * For browser-context options NOT exposed as CLI flags (locale,
 * colorScheme, geolocation coords, httpCredentials, extraHTTPHeaders)
 * we emit an init-script that runs in every page before any of the
 * page's own scripts. The script:
 *   - Overrides navigator.geolocation.getCurrentPosition with mocked coords
 *   - Patches window.matchMedia for the color-scheme preference
 *   - Overrides navigator.language / navigator.languages for locale
 *   - Wraps window.fetch / XMLHttpRequest to inject extraHTTPHeaders
 *     and a Basic auth header for httpCredentials
 *   - Auto-accepts native dialogs (alert/confirm/prompt) when the
 *     project's autoAcceptDialogs flag is true — prevents the agent
 *     from hanging on an unexpected popup
 *
 * The init-script file is generated per-session under a tmp dir keyed
 * on session id; cleaned up on session close. We do NOT cache across
 * sessions because the script embeds project-specific values.
 *
 * Sensitive bits: httpCredentials.password ends up in plaintext in the
 * init-script on disk. Tmp dir is process-owned and unlinked at session
 * close — acceptable for v1. Future hardening: pipe the script via
 * /dev/stdin or use --secrets file.
 */

const fs = require('fs');
const path = require('path');
const os = require('os');
const crypto = require('crypto');
const inPageEventRecorder = require('./inPageEventRecorder');

function parseJson(raw, fallback) {
  if (raw == null || raw === '') return fallback;
  if (typeof raw === 'object') return raw;
  try { return JSON.parse(raw); } catch (_) { return fallback; }
}

/**
 * Build the array of MCP CLI args contributed by the project's browser
 * context. Caller appends these to the base args. Returns:
 *   { cliArgs: string[], initScriptPath: string | null, downloadsDir: string }
 *
 * The downloadsDir is always set (per-session subdir) so the
 * downloadWatcher has a deterministic location to poll.
 */
function buildContextArgs(project, session) {
  const cliArgs = [];

  // ── Viewport ───────────────────────────────────────────────
  // The base buildMcpCliArgs already adds --viewport-size; the project
  // setting (when present) overrides it via the caller passing it as
  // the viewport opt to startMcpSession. We don't re-emit here.

  // ── Device emulation ───────────────────────────────────────
  if (project?.contextDevice && typeof project.contextDevice === 'string') {
    cliArgs.push('--device', project.contextDevice);
  }

  // ── User agent ─────────────────────────────────────────────
  if (project?.contextUserAgent) {
    cliArgs.push('--user-agent', project.contextUserAgent);
  }

  // ── Permissions ────────────────────────────────────────────
  const perms = parseJson(project?.contextPermissions, null);
  if (Array.isArray(perms) && perms.length) {
    // CLI takes space-separated tokens after the flag.
    cliArgs.push('--grant-permissions', ...perms.filter((p) => typeof p === 'string'));
  }

  // ── HTTPS ─────────────────────────────────────────────────
  if (project?.contextIgnoreHttpsErrors === true) {
    cliArgs.push('--ignore-https-errors');
  }

  // ── Proxy ──────────────────────────────────────────────────
  if (project?.contextProxyServer) {
    cliArgs.push('--proxy-server', project.contextProxyServer);
  }
  if (project?.contextProxyBypass) {
    cliArgs.push('--proxy-bypass', project.contextProxyBypass);
  }

  // ── Downloads dir ──────────────────────────────────────────
  // Always create a per-session subdir under playwright/test-results/downloads.
  // The downloadWatcher service polls this; cleaning happens at session close.
  const downloadsRoot = path.join(
    __dirname, '..', '..', 'playwright', 'test-results', 'downloads',
  );
  const downloadsDir = path.join(downloadsRoot, session.id);
  fs.mkdirSync(downloadsDir, { recursive: true });
  cliArgs.push('--output-dir', downloadsDir);

  // ── Init script ────────────────────────────────────────────
  // Compose ONE init-script with all the page-side shims.
  const initScriptPath = writeInitScript(project, session);
  if (initScriptPath) {
    cliArgs.push('--init-script', initScriptPath);
  }

  return { cliArgs, initScriptPath, downloadsDir };
}

/**
 * Render the per-session init script. Returns null when there's nothing
 * to inject (no project config + autoAcceptDialogs disabled).
 */
function writeInitScript(project, session) {
  const lines = [];
  lines.push(`// QAAI init-script for session ${session.id}`);
  lines.push(`// Auto-generated by mcpContextConfig.writeInitScript — do not edit by hand.`);
  lines.push('');
  lines.push('(function qaaiInit() {');
  lines.push('  try {');

  // Dialog auto-accept & visual dialog rendering — default ON unless project flag is false.
  const autoAccept = project?.autoAcceptDialogs !== false;
  lines.push('    // Dialog history buffer and visual modal');
  lines.push('    window.__qaai_dialogs = window.__qaai_dialogs || [];');
  lines.push('    window.__qaai_last_dialog = null;');
  lines.push('    window.__qaai_prompt_value = window.__qaai_prompt_value || undefined;');
  lines.push('    window.__qaai_set_prompt_value = function(val) {');
  lines.push('      window.__qaai_prompt_value = String(val != null ? val : "");');
  lines.push('      const inp = document.getElementById("qaai-dialog-prompt-input");');
  lines.push('      if (inp) inp.value = window.__qaai_prompt_value;');
  lines.push('    };');
  lines.push('    window.__qaai_close_dialog = function() {');
  lines.push('      const wrap = document.getElementById("qaai-dialog-modal-container");');
  lines.push('      if (wrap) { wrap.style.opacity = "0"; wrap.style.transition = "opacity 0.2s ease"; setTimeout(() => wrap.remove(), 200); }');
  lines.push('    };');
  lines.push('    function __qaai_render_dialog_modal(type, msg, defVal) {');
  lines.push('      try {');
  lines.push('        const old = document.getElementById("qaai-dialog-modal-container");');
  lines.push('        if (old) old.remove();');
  lines.push('        const wrap = document.createElement("div");');
  lines.push('        wrap.id = "qaai-dialog-modal-container";');
  lines.push('        wrap.style.cssText = "position:fixed;top:0;left:0;width:100vw;height:100vh;background:rgba(15,23,42,0.65);backdrop-filter:blur(5px);z-index:2147483647;display:flex;align-items:center;justify-content:center;font-family:system-ui,-apple-system,sans-serif;";');
  lines.push('        const card = document.createElement("div");');
  lines.push('        card.id = "qaai-dialog-modal";');
  lines.push('        card.style.cssText = "background:#1e293b;border:1px solid rgba(148,163,184,0.25);box-shadow:0 25px 50px -12px rgba(0,0,0,0.6);border-radius:14px;width:90%;max-width:440px;padding:22px;color:#f8fafc;display:flex;flex-direction:column;gap:14px;";');
  lines.push('        const header = document.createElement("div");');
  lines.push('        header.style.cssText = "display:flex;align-items:center;justify-content:space-between;border-bottom:1px solid rgba(148,163,184,0.15);padding-bottom:10px;";');
  lines.push('        const badge = document.createElement("span");');
  lines.push('        badge.style.cssText = "font-size:12px;font-weight:700;text-transform:uppercase;letter-spacing:0.05em;padding:3px 10px;border-radius:9999px;background:rgba(56,189,248,0.15);color:#38bdf8;border:1px solid rgba(56,189,248,0.3);";');
  lines.push('        badge.textContent = type === "prompt" ? "Prompt Dialog" : (type === "confirm" ? "Confirm Dialog" : "Alert Dialog");');
  lines.push('        const origin = document.createElement("span");');
  lines.push('        origin.style.cssText = "font-size:12px;color:#94a3b8;";');
  lines.push('        origin.textContent = window.location.hostname || "Browser Alert";');
  lines.push('        header.appendChild(badge); header.appendChild(origin);');
  lines.push('        const body = document.createElement("div");');
  lines.push('        body.id = "qaai-dialog-message";');
  lines.push('        body.style.cssText = "font-size:15px;line-height:1.5;color:#e2e8f0;word-break:break-word;";');
  lines.push('        body.textContent = String(msg || "");');
  lines.push('        let inputEl = null;');
  lines.push('        if (type === "prompt") {');
  lines.push('          inputEl = document.createElement("input");');
  lines.push('          inputEl.id = "qaai-dialog-prompt-input";');
  lines.push('          inputEl.type = "text";');
  lines.push('          inputEl.value = window.__qaai_prompt_value !== undefined ? window.__qaai_prompt_value : (defVal || "");');
  lines.push('          inputEl.style.cssText = "background:#0f172a;border:1px solid #475569;border-radius:8px;padding:8px 12px;color:#f8fafc;font-size:14px;outline:none;width:100%;box-sizing:border-box;";');
  lines.push('        }');
  lines.push('        const footer = document.createElement("div");');
  lines.push('        footer.style.cssText = "display:flex;align-items:center;justify-content:flex-end;gap:8px;padding-top:6px;";');
  lines.push('        if (type === "confirm" || type === "prompt") {');
  lines.push('          const cancelBtn = document.createElement("button");');
  lines.push('          cancelBtn.id = "qaai-dialog-cancel-btn";');
  lines.push('          cancelBtn.style.cssText = "padding:7px 15px;border-radius:8px;background:rgba(255,255,255,0.05);border:1px solid rgba(255,255,255,0.1);color:#94a3b8;font-size:13px;font-weight:600;cursor:pointer;";');
  lines.push('          cancelBtn.textContent = "Cancel";');
  lines.push('          footer.appendChild(cancelBtn);');
  lines.push('        }');
  lines.push('        const okBtn = document.createElement("button");');
  lines.push('        okBtn.id = "qaai-dialog-ok-btn";');
  lines.push('        okBtn.style.cssText = "padding:7px 18px;border-radius:8px;background:#6366f1;border:none;color:#ffffff;font-size:13px;font-weight:600;cursor:pointer;box-shadow:0 4px 12px rgba(99,102,241,0.3);";');
  lines.push('        okBtn.textContent = "OK";');
  lines.push('        footer.appendChild(okBtn);');
  lines.push('        card.appendChild(header);');
  lines.push('        card.appendChild(body);');
  lines.push('        if (inputEl) card.appendChild(inputEl);');
  lines.push('        card.appendChild(footer);');
  lines.push('        // Native browser dialogs are preserved naturally without JS function overriding.');
  lines.push('        wrap.appendChild(card);');
  lines.push('        (document.body || document.documentElement).appendChild(wrap);');
  lines.push('        setTimeout(() => {');
  lines.push('          if (wrap.parentNode) {');
  lines.push('            wrap.style.opacity = "0";');
  lines.push('            wrap.style.transition = "opacity 0.3s ease";');
  lines.push('            setTimeout(() => wrap.remove(), 300);');
  lines.push('          }');
  lines.push('        }, 3000);');
  lines.push('      } catch (_) {}');
  lines.push('    }');
  lines.push('    window.onbeforeunload = null;');
  lines.push('    try { window.addEventListener("beforeunload", function(e) { e.stopImmediatePropagation(); }, true); } catch (_) {}');

  // Evidence-only recorder. It captures event shape and selector hints, never
  // field values, and has no authority over execution or verdict decisions.
  lines.push('    // Bounded, redacted interaction evidence recorder.');
  lines.push(`    ${inPageEventRecorder.installExpression({ maxEvents: 100 })};`);

  // Locale override
  if (project?.contextLocale) {
    const loc = JSON.stringify(project.contextLocale);
    lines.push(`    // Locale override`);
    lines.push(`    Object.defineProperty(navigator, 'language', { get: () => ${loc} });`);
    lines.push(`    Object.defineProperty(navigator, 'languages', { get: () => [${loc}] });`);
  }

  // Color scheme — patch matchMedia
  if (project?.contextColorScheme) {
    const scheme = JSON.stringify(project.contextColorScheme);
    lines.push(`    // Color scheme override → ${project.contextColorScheme}`);
    lines.push(`    const _origMM = window.matchMedia;`);
    lines.push(`    window.matchMedia = function(q) {`);
    lines.push(`      if (typeof q === 'string' && q.indexOf('prefers-color-scheme') !== -1) {`);
    lines.push(`        const want = ${scheme};`);
    lines.push(`        const matches = q.indexOf(want) !== -1;`);
    lines.push(`        return { matches, media: q, onchange: null,`);
    lines.push(`          addEventListener: () => {}, removeEventListener: () => {},`);
    lines.push(`          addListener: () => {}, removeListener: () => {}, dispatchEvent: () => false };`);
    lines.push(`      }`);
    lines.push(`      return _origMM ? _origMM.call(window, q) : { matches: false, media: q, addEventListener: () => {}, removeEventListener: () => {} };`);
    lines.push(`    };`);
  }

  // Geolocation
  const geo = parseJson(project?.contextGeolocation, null);
  if (geo && typeof geo === 'object' && typeof geo.latitude === 'number' && typeof geo.longitude === 'number') {
    const geoJson = JSON.stringify({
      latitude: geo.latitude,
      longitude: geo.longitude,
      accuracy: typeof geo.accuracy === 'number' ? geo.accuracy : 50,
    });
    lines.push(`    // Geolocation override`);
    lines.push(`    if (navigator.geolocation) {`);
    lines.push(`      const _coords = ${geoJson};`);
    lines.push(`      const _pos = { coords: _coords, timestamp: Date.now() };`);
    lines.push(`      navigator.geolocation.getCurrentPosition = function(success) { try { success(_pos); } catch (_) {} };`);
    lines.push(`      navigator.geolocation.watchPosition     = function(success) { try { success(_pos); } catch (_) {} ; return 1; };`);
    lines.push(`    }`);
  }

  // Extra headers + http credentials → fetch + XHR interceptor
  const extra = parseJson(project?.contextExtraHeaders, null);
  const creds = parseJson(project?.contextHttpCredentials, null);
  const headerEntries = [];
  if (extra && typeof extra === 'object') {
    for (const [k, v] of Object.entries(extra)) {
      if (typeof k === 'string' && k && (typeof v === 'string' || typeof v === 'number')) {
        headerEntries.push([k, String(v)]);
      }
    }
  }
  if (creds && typeof creds.username === 'string' && typeof creds.password === 'string') {
    // RFC 7617 Basic auth — keep simple; servers requiring Digest will still get the header but reject it.
    const token = Buffer.from(`${creds.username}:${creds.password}`).toString('base64');
    headerEntries.push(['Authorization', `Basic ${token}`]);
  }
  if (headerEntries.length) {
    const obj = JSON.stringify(Object.fromEntries(headerEntries));
    lines.push(`    // Inject extra headers + auth on every fetch / XHR`);
    lines.push(`    const _qaaiHeaders = ${obj};`);
    lines.push(`    const _origFetch = window.fetch;`);
    lines.push(`    if (_origFetch) {`);
    lines.push(`      window.fetch = function(input, init) {`);
    lines.push(`        init = init || {};`);
    lines.push(`        const h = new Headers(init.headers || (typeof input === 'object' ? input.headers : undefined) || {});`);
    lines.push(`        Object.entries(_qaaiHeaders).forEach(function(e) { if (!h.has(e[0])) h.set(e[0], e[1]); });`);
    lines.push(`        init.headers = h;`);
    lines.push(`        return _origFetch.call(this, input, init);`);
    lines.push(`      };`);
    lines.push(`    }`);
    lines.push(`    const _XHRopen = XMLHttpRequest.prototype.open;`);
    lines.push(`    const _XHRsend = XMLHttpRequest.prototype.send;`);
    lines.push(`    XMLHttpRequest.prototype.open = function() { this.__qaaiHeaders = _qaaiHeaders; return _XHRopen.apply(this, arguments); };`);
    lines.push(`    XMLHttpRequest.prototype.send = function() {`);
    lines.push(`      try { Object.entries(this.__qaaiHeaders || {}).forEach(function(e) { try { this.setRequestHeader(e[0], e[1]); } catch (_) {} }.bind(this)); } catch (_) {}`);
    lines.push(`      return _XHRsend.apply(this, arguments);`);
    lines.push(`    };`);
  }

  // Visual Element Highlighter
  lines.push('    window.__qaai_highlight = function(el, customLabel) {');
  lines.push('      if (!el || !(el instanceof Element)) return;');
  lines.push('      try {');
  lines.push('        el.scrollIntoView({ behavior: "auto", block: "center", inline: "nearest" });');
  lines.push('      } catch (_) {}');
  lines.push('      const existing = document.getElementById("qaai-element-highlighter");');
  lines.push('      if (existing) { existing.remove(); }');
  lines.push('      const rect = el.getBoundingClientRect();');
  lines.push('      const docEl = document.documentElement;');
  lines.push('      const body = document.body;');
  lines.push('      const scrollY = window.pageYOffset || docEl.scrollTop || body.scrollTop || 0;');
  lines.push('      const scrollX = window.pageXOffset || docEl.scrollLeft || body.scrollLeft || 0;');
  lines.push('      const top = rect.top + scrollY;');
  lines.push('      const left = rect.left + scrollX;');
  lines.push('      const width = rect.width;');
  lines.push('      const height = rect.height;');
  lines.push('      const container = document.createElement("div");');
  lines.push('      container.id = "qaai-element-highlighter";');
  lines.push('      container.style.position = "absolute";');
  lines.push('      container.style.top = top + "px";');
  lines.push('      container.style.left = left + "px";');
  lines.push('      container.style.width = width + "px";');
  lines.push('      container.style.height = height + "px";');
  lines.push('      container.style.border = "3px solid #a855f7";');
  lines.push('      container.style.backgroundColor = "rgba(168, 85, 247, 0.15)";');
  lines.push('      container.style.pointerEvents = "none";');
  lines.push('      container.style.zIndex = "2147483647";');
  lines.push('      container.style.boxSizing = "border-box";');
  lines.push('      container.style.borderRadius = "4px";');
  lines.push('      container.style.transition = "opacity 0.3s ease-out";');
  lines.push('      const label = document.createElement("div");');
  lines.push('      label.style.position = "absolute";');
  lines.push('      label.style.top = (rect.top > 25 ? "-25px" : "0px");');
  lines.push('      label.style.left = "0px";');
  lines.push('      label.style.backgroundColor = "#a855f7";');
  lines.push('      label.style.color = "#ffffff";');
  lines.push('      label.style.fontSize = "11px";');
  lines.push('      label.style.fontFamily = "monospace";');
  lines.push('      label.style.fontWeight = "bold";');
  lines.push('      label.style.padding = "2px 6px";');
  lines.push('      label.style.borderRadius = "3px";');
  lines.push('      label.style.whiteSpace = "nowrap";');
  lines.push('      let elLabel = customLabel || (el.labels && el.labels[0] && el.labels[0].textContent) || el.getAttribute("aria-label") || (el.previousElementSibling?.tagName === "LABEL" ? el.previousElementSibling.textContent : null) || (el.parentElement?.tagName === "LABEL" ? el.parentElement.textContent : null) || el.placeholder || el.textContent?.trim().slice(0, 30) || el.name || el.id || el.tagName.toLowerCase();');
  lines.push('      elLabel = String(elLabel || "").trim();');
  lines.push('      if (el.disabled || el.getAttribute("aria-disabled") === "true") { if (!elLabel.includes("(disabled)")) elLabel += " (disabled)"; }');
  lines.push('      if (el.readOnly || el.hasAttribute("readonly")) { if (!elLabel.includes("(readonly)")) elLabel += " (readonly)"; }');
  lines.push('      label.textContent = elLabel;');
  lines.push('      container.appendChild(label);');
  lines.push('      document.body.appendChild(container);');
  lines.push('      setTimeout(() => {');
  lines.push('        if (container.parentNode) {');
  lines.push('          container.style.opacity = "0";');
  lines.push('          setTimeout(() => {');
  lines.push('            if (container.parentNode) { container.parentNode.removeChild(container); }');
  lines.push('          }, 300);');
  lines.push('        }');
  lines.push('      }, 3000);');
  lines.push('    };');

  lines.push('  } catch (e) {');
  lines.push('    // Never let the init-script break the page.');
  lines.push('    try { console.warn("[qaai-init] error", e && e.message); } catch (_) {}');
  lines.push('  }');
  lines.push('})();');

  const body = lines.join('\n');
  // Skip writing if effectively empty — only the wrapper and the always-on
  // dialog block (which is itself opt-out). Detect that case to keep tmp clean.
  // (We always emit the file when autoAcceptDialogs is true OR when any
  // shim block fired — the body length tells us.)
  if (body.split('\n').length <= 7) return null;

  const tmpDir = path.join(os.tmpdir(), 'qaai-mcp-init');
  fs.mkdirSync(tmpDir, { recursive: true });
  const filePath = path.join(tmpDir, `init-${session.id}-${crypto.randomBytes(4).toString('hex')}.js`);
  fs.writeFileSync(filePath, body, 'utf8');
  return filePath;
}

/**
 * Best-effort cleanup of the init-script + downloads dir at session close.
 * Errors are swallowed — leftover files are harmless and the tmp dir gets
 * cleaned by the OS.
 */
function cleanupContextArtifacts({ initScriptPath, downloadsDir, keepDownloads }) {
  if (initScriptPath) {
    try { fs.unlinkSync(initScriptPath); } catch (_) {}
  }
  if (downloadsDir && !keepDownloads) {
    try { fs.rmSync(downloadsDir, { recursive: true, force: true }); } catch (_) {}
  }
}

module.exports = { buildContextArgs, cleanupContextArtifacts };
