'use strict';

/**
 * Browser-context configuration for the @playwright/mcp subprocess
 * (Phase E10.5).
 *
 * @playwright/mcp accepts most browser-context flags via its CLI:
 *   --viewport-size, --device, --user-agent, --grant-permissions,
 *   --ignore-https-errors, --proxy-server, --proxy-bypass, --init-script,
 *   --output-dir, --test-id-attribute.
 *
 * For browser-context options NOT exposed as CLI flags (locale,
 * colorScheme, geolocation coords, httpCredentials, extraHTTPHeaders)
 * we emit an init-script that runs in every page before any of the
 * page's own scripts. The script:
 *   - Overrides navigator.geolocation.getCurrentPosition with mocked coords
 *   - Patches window.matchMedia for the color-scheme preference
 *   - Overrides navigator.language / navigator.languages for locale
 *   - Wraps window.fetch / XMLHttpRequest to inject extraHTTPHeaders
 *     and a Basic auth header for httpCredentials
 *   - Auto-accepts native dialogs (alert/confirm/prompt) when the
 *     project's autoAcceptDialogs flag is true — prevents the agent
 *     from hanging on an unexpected popup
 *
 * The init-script file is generated per-session under a tmp dir keyed
 * on session id; cleaned up on session close. We do NOT cache across
 * sessions because the script embeds project-specific values.
 *
 * Sensitive bits: httpCredentials.password ends up in plaintext in the
 * init-script on disk. Tmp dir is process-owned and unlinked at session
 * close — acceptable for v1. Future hardening: pipe the script via
 * /dev/stdin or use --secrets file.
 */

const fs = require('fs');
const path = require('path');
const os = require('os');
const crypto = require('crypto');
const inPageEventRecorder = require('./inPageEventRecorder');

function parseJson(raw, fallback) {
  if (raw == null || raw === '') return fallback;
  if (typeof raw === 'object') return raw;
  try { return JSON.parse(raw); } catch (_) { return fallback; }
}

/**
 * Build the array of MCP CLI args contributed by the project's browser
 * context. Caller appends these to the base args. Returns:
 *   { cliArgs: string[], initScriptPath: string | null, downloadsDir: string }
 *
 * The downloadsDir is always set (per-session subdir) so the
 * downloadWatcher has a deterministic location to poll.
 */
function buildContextArgs(project, session) {
  const cliArgs = [];

  // ── Viewport ───────────────────────────────────────────────
  // The base buildMcpCliArgs already adds --viewport-size; the project
  // setting (when present) overrides it via the caller passing it as
  // the viewport opt to startMcpSession. We don't re-emit here.

  // ── Device emulation ───────────────────────────────────────
  if (project?.contextDevice && typeof project.contextDevice === 'string') {
    cliArgs.push('--device', project.contextDevice);
  }

  // ── User agent ─────────────────────────────────────────────
  if (project?.contextUserAgent) {
    cliArgs.push('--user-agent', project.contextUserAgent);
  }

  // ── Permissions ────────────────────────────────────────────
  const perms = parseJson(project?.contextPermissions, null);
  if (Array.isArray(perms) && perms.length) {
    // CLI takes space-separated tokens after the flag.
    cliArgs.push('--grant-permissions', ...perms.filter((p) => typeof p === 'string'));
  }

  // ── HTTPS ─────────────────────────────────────────────────
  if (project?.contextIgnoreHttpsErrors === true) {
    cliArgs.push('--ignore-https-errors');
  }

  // ── Proxy ──────────────────────────────────────────────────
  if (project?.contextProxyServer) {
    cliArgs.push('--proxy-server', project.contextProxyServer);
  }
  if (project?.contextProxyBypass) {
    cliArgs.push('--proxy-bypass', project.contextProxyBypass);
  }

  // ── Downloads dir ──────────────────────────────────────────
  // Always create a per-session subdir under playwright/test-results/downloads.
  // The downloadWatcher service polls this; cleaning happens at session close.
  const downloadsRoot = path.join(
    __dirname, '..', '..', 'playwright', 'test-results', 'downloads',
  );
  const downloadsDir = path.join(downloadsRoot, session.id);
  fs.mkdirSync(downloadsDir, { recursive: true });
  cliArgs.push('--output-dir', downloadsDir);

  // ── Init script ────────────────────────────────────────────
  // Compose ONE init-script with all the page-side shims.
  const initScriptPath = writeInitScript(project, session);
  if (initScriptPath) {
    cliArgs.push('--init-script', initScriptPath);
  }

  return { cliArgs, initScriptPath, downloadsDir };
}

/**
 * Render the per-session init script. Returns null when there's nothing
 * to inject (no project config + autoAcceptDialogs disabled).
 */
function writeInitScript(project, session) {
  const lines = [];
  lines.push(`// QAAI init-script for session ${session.id}`);
  lines.push(`// Auto-generated by mcpContextConfig.writeInitScript — do not edit by hand.`);
  lines.push('');
  lines.push('(function qaaiInit() {');
  lines.push('  try {');

  // Dialog auto-accept — default ON unless project flag is false.
  const autoAccept = project?.autoAcceptDialogs !== false;
  if (autoAccept) {
    lines.push('    // E10.5 — Auto-accept unexpected dialogs so the agent does not hang.');
    lines.push('    window.alert = function(_msg) {};');
    lines.push('    window.confirm = function(_msg) { return true; };');
    lines.push('    window.prompt = function(_msg, def) { return def != null ? String(def) : ""; };');
  }

  // Evidence-only recorder. It captures event shape and selector hints, never
  // field values, and has no authority over execution or verdict decisions.
  lines.push('    // Bounded, redacted interaction evidence recorder.');
  lines.push(`    ${inPageEventRecorder.installExpression({ maxEvents: 100 })};`);

  // Locale override
  if (project?.contextLocale) {
    const loc = JSON.stringify(project.contextLocale);
    lines.push(`    // Locale override`);
    lines.push(`    Object.defineProperty(navigator, 'language', { get: () => ${loc} });`);
    lines.push(`    Object.defineProperty(navigator, 'languages', { get: () => [${loc}] });`);
  }

  // Color scheme — patch matchMedia
  if (project?.contextColorScheme) {
    const scheme = JSON.stringify(project.contextColorScheme);
    lines.push(`    // Color scheme override → ${project.contextColorScheme}`);
    lines.push(`    const _origMM = window.matchMedia;`);
    lines.push(`    window.matchMedia = function(q) {`);
    lines.push(`      if (typeof q === 'string' && q.indexOf('prefers-color-scheme') !== -1) {`);
    lines.push(`        const want = ${scheme};`);
    lines.push(`        const matches = q.indexOf(want) !== -1;`);
    lines.push(`        return { matches, media: q, onchange: null,`);
    lines.push(`          addEventListener: () => {}, removeEventListener: () => {},`);
    lines.push(`          addListener: () => {}, removeListener: () => {}, dispatchEvent: () => false };`);
    lines.push(`      }`);
    lines.push(`      return _origMM ? _origMM.call(window, q) : { matches: false, media: q, addEventListener: () => {}, removeEventListener: () => {} };`);
    lines.push(`    };`);
  }

  // Geolocation
  const geo = parseJson(project?.contextGeolocation, null);
  if (geo && typeof geo === 'object' && typeof geo.latitude === 'number' && typeof geo.longitude === 'number') {
    const geoJson = JSON.stringify({
      latitude: geo.latitude,
      longitude: geo.longitude,
      accuracy: typeof geo.accuracy === 'number' ? geo.accuracy : 50,
    });
    lines.push(`    // Geolocation override`);
    lines.push(`    if (navigator.geolocation) {`);
    lines.push(`      const _coords = ${geoJson};`);
    lines.push(`      const _pos = { coords: _coords, timestamp: Date.now() };`);
    lines.push(`      navigator.geolocation.getCurrentPosition = function(success) { try { success(_pos); } catch (_) {} };`);
    lines.push(`      navigator.geolocation.watchPosition     = function(success) { try { success(_pos); } catch (_) {} ; return 1; };`);
    lines.push(`    }`);
  }

  // Extra headers + http credentials → fetch + XHR interceptor
  const extra = parseJson(project?.contextExtraHeaders, null);
  const creds = parseJson(project?.contextHttpCredentials, null);
  const headerEntries = [];
  if (extra && typeof extra === 'object') {
    for (const [k, v] of Object.entries(extra)) {
      if (typeof k === 'string' && k && (typeof v === 'string' || typeof v === 'number')) {
        headerEntries.push([k, String(v)]);
      }
    }
  }
  if (creds && typeof creds.username === 'string' && typeof creds.password === 'string') {
    // RFC 7617 Basic auth — keep simple; servers requiring Digest will still get the header but reject it.
    const token = Buffer.from(`${creds.username}:${creds.password}`).toString('base64');
    headerEntries.push(['Authorization', `Basic ${token}`]);
  }
  if (headerEntries.length) {
    const obj = JSON.stringify(Object.fromEntries(headerEntries));
    lines.push(`    // Inject extra headers + auth on every fetch / XHR`);
    lines.push(`    const _qaaiHeaders = ${obj};`);
    lines.push(`    const _origFetch = window.fetch;`);
    lines.push(`    if (_origFetch) {`);
    lines.push(`      window.fetch = function(input, init) {`);
    lines.push(`        init = init || {};`);
    lines.push(`        const h = new Headers(init.headers || (typeof input === 'object' ? input.headers : undefined) || {});`);
    lines.push(`        Object.entries(_qaaiHeaders).forEach(function(e) { if (!h.has(e[0])) h.set(e[0], e[1]); });`);
    lines.push(`        init.headers = h;`);
    lines.push(`        return _origFetch.call(this, input, init);`);
    lines.push(`      };`);
    lines.push(`    }`);
    lines.push(`    const _XHRopen = XMLHttpRequest.prototype.open;`);
    lines.push(`    const _XHRsend = XMLHttpRequest.prototype.send;`);
    lines.push(`    XMLHttpRequest.prototype.open = function() { this.__qaaiHeaders = _qaaiHeaders; return _XHRopen.apply(this, arguments); };`);
    lines.push(`    XMLHttpRequest.prototype.send = function() {`);
    lines.push(`      try { Object.entries(this.__qaaiHeaders || {}).forEach(function(e) { try { this.setRequestHeader(e[0], e[1]); } catch (_) {} }.bind(this)); } catch (_) {}`);
    lines.push(`      return _XHRsend.apply(this, arguments);`);
    lines.push(`    };`);
  }

  // Visual Element Highlighter
  lines.push('    window.__qaai_highlight = function(el) {');
  lines.push('      if (!el || !(el instanceof Element)) return;');
  lines.push('      const existing = document.getElementById("qaai-element-highlighter");');
  lines.push('      if (existing) { existing.remove(); }');
  lines.push('      const rect = el.getBoundingClientRect();');
  lines.push('      const docEl = document.documentElement;');
  lines.push('      const body = document.body;');
  lines.push('      const scrollY = window.pageYOffset || docEl.scrollTop || body.scrollTop || 0;');
  lines.push('      const scrollX = window.pageXOffset || docEl.scrollLeft || body.scrollLeft || 0;');
  lines.push('      const top = rect.top + scrollY;');
  lines.push('      const left = rect.left + scrollX;');
  lines.push('      const width = rect.width;');
  lines.push('      const height = rect.height;');
  lines.push('      const container = document.createElement("div");');
  lines.push('      container.id = "qaai-element-highlighter";');
  lines.push('      container.style.position = "absolute";');
  lines.push('      container.style.top = top + "px";');
  lines.push('      container.style.left = left + "px";');
  lines.push('      container.style.width = width + "px";');
  lines.push('      container.style.height = height + "px";');
  lines.push('      container.style.border = "3px solid #a855f7";');
  lines.push('      container.style.backgroundColor = "rgba(168, 85, 247, 0.15)";');
  lines.push('      container.style.pointerEvents = "none";');
  lines.push('      container.style.zIndex = "2147483647";');
  lines.push('      container.style.boxSizing = "border-box";');
  lines.push('      container.style.borderRadius = "4px";');
  lines.push('      container.style.transition = "opacity 0.3s ease-out";');
  lines.push('      const label = document.createElement("div");');
  lines.push('      label.style.position = "absolute";');
  lines.push('      label.style.top = (rect.top > 25 ? "-25px" : "0px");');
  lines.push('      label.style.left = "0px";');
  lines.push('      label.style.backgroundColor = "#a855f7";');
  lines.push('      label.style.color = "#ffffff";');
  lines.push('      label.style.fontSize = "11px";');
  lines.push('      label.style.fontFamily = "monospace";');
  lines.push('      label.style.fontWeight = "bold";');
  lines.push('      label.style.padding = "2px 6px";');
  lines.push('      label.style.borderRadius = "3px";');
  lines.push('      label.style.whiteSpace = "nowrap";');
  lines.push('      let elLabel = el.getAttribute("aria-label") || el.placeholder || (el.labels && el.labels[0] && el.labels[0].textContent) || el.textContent?.trim().slice(0, 30) || el.name || el.id || el.tagName.toLowerCase();');
  lines.push('      elLabel = String(elLabel || "").trim();');
  lines.push('      if (el.disabled || el.getAttribute("aria-disabled") === "true") { elLabel += " (disabled)"; }');
  lines.push('      label.textContent = elLabel;');
  lines.push('      container.appendChild(label);');
  lines.push('      document.body.appendChild(container);');
  lines.push('      setTimeout(() => {');
  lines.push('        if (container.parentNode) {');
  lines.push('          container.style.opacity = "0";');
  lines.push('          setTimeout(() => {');
  lines.push('            if (container.parentNode) { container.parentNode.removeChild(container); }');
  lines.push('          }, 300);');
  lines.push('        }');
  lines.push('      }, 3000);');
  lines.push('    };');

  lines.push('  } catch (e) {');
  lines.push('    // Never let the init-script break the page.');
  lines.push('    try { console.warn("[qaai-init] error", e && e.message); } catch (_) {}');
  lines.push('  }');
  lines.push('})();');

  const body = lines.join('\n');
  // Skip writing if effectively empty — only the wrapper and the always-on
  // dialog block (which is itself opt-out). Detect that case to keep tmp clean.
  // (We always emit the file when autoAcceptDialogs is true OR when any
  // shim block fired — the body length tells us.)
  if (body.split('\n').length <= 7) return null;

  const tmpDir = path.join(os.tmpdir(), 'qaai-mcp-init');
  fs.mkdirSync(tmpDir, { recursive: true });
  const filePath = path.join(tmpDir, `init-${session.id}-${crypto.randomBytes(4).toString('hex')}.js`);
  fs.writeFileSync(filePath, body, 'utf8');
  return filePath;
}

/**
 * Best-effort cleanup of the init-script + downloads dir at session close.
 * Errors are swallowed — leftover files are harmless and the tmp dir gets
 * cleaned by the OS.
 */
function cleanupContextArtifacts({ initScriptPath, downloadsDir, keepDownloads }) {
  if (initScriptPath) {
    try { fs.unlinkSync(initScriptPath); } catch (_) {}
  }
  if (downloadsDir && !keepDownloads) {
    try { fs.rmSync(downloadsDir, { recursive: true, force: true }); } catch (_) {}
  }
}

module.exports = { buildContextArgs, cleanupContextArtifacts };
