'use strict';

const {
  VALID_STEP_TYPES,
  VALID_ASSERTION_TYPES,
  isCanonicalDate,
  isCanonicalTime,
  isCanonicalDateTime,
} = require('./caseContractSemanticValidator');

const CONTRACT_VERSION = 'OperationContractV2';

const OPERATION_KIND = Object.freeze({
  ACTION: 'action',
  ASSERTION: 'assertion',
  SYNCHRONIZATION: 'synchronization',
});

const TARGET_OPTIONAL_ACTIONS = new Set([
  'Navigate', 'GoBack', 'GoForward', 'Refresh',
  'SwitchContext', 'SwitchTab', 'Close', 'Screenshot', 'PressKey', 'Hotkey',
  'AcceptAlert', 'DismissAlert', 'Copy', 'Paste', 'Evaluate', 'Semantic',
]);
// Pure navigation/whole-page controls that structurally can never have a
// real UI target (unlike e.g. Screenshot/PressKey/SwitchTab, which
// sometimes legitimately scope to one). Any inherited targetIdentity on
// these is noise, not signal.
const NEVER_HAS_TARGET_ACTIONS = new Set(['Navigate', 'GoBack', 'GoForward', 'Refresh']);
const VALUE_REQUIRED_ACTIONS = new Set([
  'Fill',
  'Type',
  'ClearAndType',
  'Date',
  'Time',
  'DateTime',
  'Upload',
  'PressKey',
  'Hotkey',
  'TypeAlert',
  'ExtractData',
  'StoreVariable',
]);
const VALUE_OPTIONAL_ACTIONS = new Set(['Navigate', 'Select', 'Radio', 'Deselect', 'MultiSelect', 'Slider', 'SwitchTab', 'ExtractData', 'ClickAndHold', 'Evaluate', 'Semantic']);
const VALUE_ACTIONS = new Set([...VALUE_REQUIRED_ACTIONS, ...VALUE_OPTIONAL_ACTIONS]);
const ASSERTION_POLLUTION_RE = /(?:,\s*|\s+)(?:and\s+)?(?:verify|assert|validate|confirm|expect)(?:\s+that)?\b/i;
const CHAINED_ACTION_RE = /\b(?:and\s+then|then)\s+(?:click|press|select|choose|fill|enter|type|submit|open)\b/i;
const CONTROL_WORDS_RE = /\b(?:dropdown|combobox|listbox|menu|calendar|date picker|time picker|textbox|field|input|control|button|link)\b/ig;

class OperationContractError extends Error {
  constructor(message, findings = []) {
    super(message);
    this.name = 'OperationContractError';
    this.code = 'OPERATION_CONTRACT_INVALID';
    this.findings = Object.freeze(findings.map((finding) => Object.freeze({ ...finding })));
  }
}

// ── Step type inference from free-form action text ─────────────────────────
// Steps authored via the UI or generated by the Architect may store the full
// human-readable instruction in `action` without a separate `type` field.
// This function recovers the canonical VALID_STEP_TYPES member from that text.
// Order matters: more specific patterns (PressKey) must precede generic ones.
const TYPE_INFERENCE_RULES = [
  { pattern: /^\s*(?:navigate\s+back|go\s+back)\b/i, type: 'GoBack' },
  { pattern: /^\s*(?:navigate\s+forward|go\s+forward)\b/i, type: 'GoForward' },
  { pattern: /^\s*(?:refresh|reload)\b/i, type: 'Refresh' },
  { pattern: /^\s*(?:navigate|go\s+to|visit|load)\b/i, type: 'Navigate' },
  { pattern: /^\s*open\b/i, type: 'Navigate' },
  // Mouse gestures
  { pattern: /^\s*(?:right\s*click|context\s*menu)\b/i, type: 'RightClick' },
  { pattern: /^\s*(?:middle\s*click|aux\s*click)\b/i, type: 'MiddleClick' },
  { pattern: /^\s*(?:click\s*and\s*hold|hold\s+button|long\s*press|press\s*and\s*hold)\b/i, type: 'ClickAndHold' },
  { pattern: /^\s*(?:double\s*click)\b/i, type: 'DoubleClick' },
  // Shortcuts & Keys
  { pattern: /^\s*(?:press\s+shortcut|hotkey|press\s+combination|key\s+combination)\b/i, type: 'Hotkey' },
  { pattern: /^\s*press\s+(?:the\s+)?(?:tab|enter|escape|backspace|delete|arrow\w*|control|alt|shift|space|home|end|page\s*(?:up|down)|f\d{1,2})\b/i, type: 'PressKey' },
  // Dialogs & Alerts
  { pattern: /^\s*(?:accept\s+(?:the\s+)?alert|confirm\s+(?:the\s+)?alert|ok\s+(?:the\s+)?alert)\b/i, type: 'AcceptAlert' },
  { pattern: /^\s*(?:dismiss\s+(?:the\s+)?alert|cancel\s+(?:the\s+)?alert)\b/i, type: 'DismissAlert' },
  { pattern: /^\s*(?:type|enter|input)\s+into\s+(?:the\s+)?(?:prompt|alert)\b/i, type: 'TypeAlert' },
  // Data & Clipboard
  { pattern: /^\s*(?:copy|copy\s+to\s+clipboard)\b/i, type: 'Copy' },
  { pattern: /^\s*(?:paste|paste\s+from\s+clipboard)\b/i, type: 'Paste' },
  { pattern: /^\s*(?:extract\s+data|extract|save\s+to\s+variable|store\s+variable|record)\b/i, type: 'ExtractData' },
  { pattern: /^\s*(?:evaluate|execute\s*script|run\s*script)\b/i, type: 'Evaluate' },
  { pattern: /^\s*(?:human_input|human_verification|manual|human|prompt_user)\b/i, type: 'WaitForState' },
  // Window & Frame isolation
  { pattern: /^\s*(?:switch\s+to\s+tab|switch\s+tab|switch\s+window)\b/i, type: 'SwitchTab' },
  { pattern: /^\s*(?:switch\s+to\s+frame|switch\s+frame|enter\s+iframe)\b/i, type: 'SwitchFrame' },
  { pattern: /^\s*(?:access\s+shadow|enter\s+shadow|access\s+open\s+shadow|access\s+closed\s+shadow)\b/i, type: 'AccessShadow' },
  { pattern: /^\s*(?:switch\s*(?:to|context))\b/i, type: 'SwitchContext' },
  // Inputs
  { pattern: /^\s*append\b/i, type: 'Type' },
  { pattern: /^\s*clear\s+and\s+(?:type|enter|fill)\b/i, type: 'ClearAndType' },
  { pattern: /^\s*clear\b/i, type: 'Clear' },
  { pattern: /^\s*(?:drag\s+and\s+drop|drag)\b/i, type: 'DragAndDrop' },
  { pattern: /^\s*(?:set\s+slider|adjust\s+slider|slide)\b/i, type: 'Slider' },
  { pattern: /^\s*(?:enter|fill|type|input|provide|populate)\b/i, type: 'Fill' },
  { pattern: /^\s*deselect\b/i, type: 'Deselect' },
  { pattern: /^\s*(?:select|choose|pick)\b/i, type: 'Select' },
  { pattern: /^\s*uncheck\b/i, type: 'Uncheck' },
  { pattern: /^\s*check\b/i, type: 'Check' },
  { pattern: /^\s*(?:click|tap|submit)\b/i, type: 'Click' },
  { pattern: /^\s*press\b/i, type: 'Click' },
  { pattern: /^\s*upload\b/i, type: 'Upload' },
  { pattern: /^\s*download\b/i, type: 'Download' },
  { pattern: /^\s*(?:wait|pause)\b/i, type: 'WaitForState' },
  { pattern: /^\s*hover\b/i, type: 'Hover' },
  { pattern: /^\s*(?:scroll\s+into\s+view|scroll\s+to)\b/i, type: 'ScrollIntoView' },
  { pattern: /^\s*scroll\b/i, type: 'Scroll' },
  { pattern: /^\s*(?:expand)\b/i, type: 'Expand' },
  { pattern: /^\s*(?:collapse)\b/i, type: 'Collapse' },
  { pattern: /^\s*screenshot\b/i, type: 'Screenshot' },
  { pattern: /^\s*close\b/i, type: 'Close' },
  // Table operations
  { pattern: /^\s*(?:find\s+row|locate\s+row)\b/i, type: 'FindRow' },
  { pattern: /^\s*(?:count\s+rows|count\s+visible)\b/i, type: 'CountRows' },
  { pattern: /^\s*(?:sort|click\s+header)\b/i, type: 'SortColumn' },
];

// Returns true if the action text describes a verification / confirmation step
// that should be compiled as an assertion, not an action.
const ASSERTION_LIKE_RE = /^\s*(?:verify|validate|assert|expect|confirm|ensure|check\s+(?:that|if|whether))\b/i;

function inferCanonicalType(actionText) {
  const text = String(actionText || '').trim();
  if (!text) return null;
  // If it already IS a valid step type (e.g. "Fill"), use it directly.
  if (VALID_STEP_TYPES.includes(text)) return text;
  const rule = TYPE_INFERENCE_RULES.find(({ pattern }) => pattern.test(text));
  return rule ? rule.type : null;
}

function isAssertionLikeAction(actionText) {
  return ASSERTION_LIKE_RE.test(String(actionText || '').trim());
}

// Infer the specific VALID_ASSERTION_TYPES member from free-form text.
// E.g. "Confirm the field is disabled" → AssertDisabled.
function inferAssertionType(actionText) {
  const text = String(actionText || '').trim().toLowerCase();
  if (!text) return null;
  if (/\bdisabled\b/.test(text)) return 'AssertDisabled';
  if (/\bread[\s-]*only\b/.test(text)) return 'AssertReadonly';
  if (/\benabled\b/.test(text)) return 'AssertEnabled';
  if (/\bhidden\b/.test(text)) return 'AssertHidden';
  if (/\bvisible\b|\bdisplayed\b|\bshown\b|\bappears?\b/.test(text)) return 'AssertVisible';
  if (/\bchecked\b/.test(text)) return 'AssertChecked';
  if (/\bselected\b/.test(text)) return 'AssertSelected';
  if (/\burl\b|\baddress\b|\blocation\b/.test(text)) return 'AssertUrl';
  if (/\bcount\b|\bnumber of\b/.test(text)) return 'AssertCount';
  if (/\bvalue\b|\bcontains?\b|\btext\b|\binside\b/.test(text)) return 'AssertText';
  return 'AssertVisible'; // safe fallback — existence check
}

function isObject(value) {
  return Boolean(value) && typeof value === 'object' && !Array.isArray(value);
}

function clone(value) {
  if (Array.isArray(value)) return value.map(clone);
  if (!isObject(value)) return value;
  return Object.fromEntries(Object.entries(value).map(([key, item]) => [key, clone(item)]));
}

function clean(value) {
  return String(value == null ? '' : value).replace(/\s+/g, ' ').trim();
}

function stableIdPart(value) {
  return clean(value).replace(/[^A-Za-z0-9._:-]+/g, '-').replace(/^-+|-+$/g, '');
}

function finding(path, code, message, received = undefined) {
  return {
    path,
    code,
    message,
    ...(received === undefined ? {} : { received: clone(received) }),
  };
}

function containsPollutedInstruction(value) {
  const text = clean(value);
  return ASSERTION_POLLUTION_RE.test(text) || CHAINED_ACTION_RE.test(text);
}

function textFromTarget(target) {
  if (typeof target === 'string') return clean(target);
  if (!isObject(target)) return '';
  return clean(
    target.accessibleName
      || target.label
      || target.name
      || target.text
      || target.reference
      || target.testId,
  );
}

function normalizeFramePath(value) {
  if (Array.isArray(value)) return value.map(clean).filter(Boolean);
  const text = clean(value);
  return text ? [text] : [];
}

function normalizeTargetIdentity(value, path, findings) {
  if (typeof value === 'string') {
    const label = clean(value);
    if (!label) {
      findings.push(finding(path, 'target_identity_empty', 'Target identity cannot be empty.'));
      return null;
    }
    if (containsPollutedInstruction(label)) {
      findings.push(finding(
        path,
        'target_identity_contains_instructions',
        'Target identity contains another action or assertion instruction.',
        label,
      ));
    }
    return Object.freeze({
      label,
      accessibleName: label,
      role: null,
      framePath: Object.freeze([]),
      form: null,
      section: null,
      controlType: null,
      backendNodeId: null,
    });
  }
  if (!isObject(value)) {
    findings.push(finding(path, 'target_identity_required', 'An explicit target identity is required.'));
    return null;
  }

  const label = textFromTarget(value);
  if (!label) {
    findings.push(finding(
      path,
      'target_identity_name_required',
      'Target identity requires an authored accessible name, label, reference, or test id.',
    ));
  } else if (containsPollutedInstruction(label)) {
    findings.push(finding(
      path,
      'target_identity_contains_instructions',
      'Target identity contains another action or assertion instruction.',
      label,
    ));
  }

  const role = clean(value.role) || null;
  const framePath = normalizeFramePath(value.framePath || value.frame || value.frameId);
  const form = clean(value.form || value.formName || value.formId) || null;
  const section = clean(value.section || value.scope || value.region) || null;
  const controlType = clean(value.controlType || value.type || value.inputType) || null;
  const backendNodeId = clean(value.backendNodeId || value.nodeId) || null;
  return Object.freeze({
    kind: clean(value.kind) || null,
    label: label || null,
    accessibleName: clean(value.accessibleName || value.name || value.label) || label || null,
    role,
    framePath: Object.freeze(framePath),
    form,
    section,
    controlType,
    backendNodeId,
    testId: clean(value.testId || value.qaaiId) || null,
    reference: clean(value.reference || value.ref) || null,
  });
}

function normalizeSelection(value, path, findings, { exactAuthoredValue = null } = {}) {
  const canonicalAuthoredValue = clean(exactAuthoredValue);
  if (canonicalAuthoredValue) {
    if (containsPollutedInstruction(canonicalAuthoredValue)) {
      findings.push(finding(
        path,
        'selection_contains_assertion_prose',
        'Selection contains assertion prose and is unsafe to execute.',
        canonicalAuthoredValue,
      ));
    }
    return Object.freeze({ kind: 'exact_text', value: canonicalAuthoredValue });
  }
  if (typeof value === 'string' || typeof value === 'number') {
    const exactText = clean(value);
    if (!exactText) {
      findings.push(finding(path, 'selection_empty', 'Selection cannot be empty.'));
      return null;
    }
    if (containsPollutedInstruction(exactText)) {
      findings.push(finding(
        path,
        'selection_contains_assertion_prose',
        'Selection contains assertion prose and is unsafe to execute.',
        exactText,
      ));
    }
    return Object.freeze({ kind: 'exact_text', value: exactText });
  }
  if (!isObject(value)) {
    findings.push(finding(path, 'selection_required', 'Select requires an explicit selection contract.'));
    return null;
  }
  const kind = clean(value.kind) || (
    value.text != null ? 'exact_text'
      : value.value != null ? 'exact_value'
        : value.ordinal != null ? 'ordinal'
          : value.ref != null ? 'reference'
            : null
  );
  const criterion = value.text
    ?? value.expectedText
    ?? value.value
    ?? value.ordinal
    ?? value.ref
    ?? value.reference
    ?? value.description
    ?? value.predicate;
  if (!kind || criterion == null || clean(criterion) === '') {
    findings.push(finding(path, 'selection_criterion_required', 'Selection requires one exact criterion.', value));
    return null;
  }
  if (typeof criterion === 'string' && containsPollutedInstruction(criterion)) {
    findings.push(finding(
      path,
      'selection_contains_assertion_prose',
      'Selection contains assertion prose and is unsafe to execute.',
      criterion,
    ));
  }
  return Object.freeze({ kind, value: clone(criterion) });
}

function normalizeValue(type, source, path, findings) {
  // A `value` key present but explicitly null means "no value" — the same as
  // the key being absent. The user-authored step-edit pipeline
  // (testCaseStepMutations.js#inferExecutionFields) always emits a `value`
  // key, null when there is nothing to set, for every action type including
  // ones that never take a value (WaitForState, Click, AssertVisible, ...).
  // Checking raw key-presence here treated that null as "has a value" and
  // rejected every edited non-value-action step as invalid — a step that
  // compiled fine before being edited even once through the UI's own edit
  // feature. This must key off whether the value is actually meaningful.
  const hasValue = Object.prototype.hasOwnProperty.call(source, 'value') && source.value !== null;
  const valueRef = clean(source.valueRef) || null;
  if (!VALUE_ACTIONS.has(type)) {
    return Object.freeze({ value: null, valueRef: null });
  }
  if (VALUE_REQUIRED_ACTIONS.has(type) && !hasValue && !valueRef) {
    findings.push(finding(path, 'action_value_required', `${type} requires value or valueRef.`));
    return Object.freeze({ value: null, valueRef: null });
  }
  const value = hasValue ? clone(source.value) : null;
  if (typeof value === 'string' && containsPollutedInstruction(value)) {
    findings.push(finding(
      `${path}.value`,
      'action_value_contains_assertion_prose',
      'Action value contains assertion prose and is unsafe to execute.',
      value,
    ));
  }
  if (type === 'Date' && value != null && !isCanonicalDate(value)) {
    findings.push(finding(`${path}.value`, 'date_value_not_canonical', 'Date must use YYYY-MM-DD.', value));
  }
  if (type === 'Time' && value != null && !isCanonicalTime(value)) {
    findings.push(finding(`${path}.value`, 'time_value_not_canonical', 'Time must use 24-hour HH:mm or HH:mm:ss.', value));
  }
  if (type === 'DateTime' && value != null && !isCanonicalDateTime(value)) {
    findings.push(finding(`${path}.value`, 'datetime_value_not_canonical', 'DateTime must be timezone-qualified ISO-8601.', value));
  }
  return Object.freeze({ value, valueRef });
}

function normalizeDependencies(value) {
  return Object.freeze([
    ...new Set((Array.isArray(value) ? value : []).map(clean).filter(Boolean)),
  ]);
}

function normalizeTargetAliases(source, targetIdentity) {
  const primary = clean(targetIdentity?.accessibleName || targetIdentity?.label);
  return Object.freeze([
    ...new Set([
      source.element,
      source.label,
      source.accessibleName,
      source.text,
    ].map(clean).filter((value) => value && value !== primary && !containsPollutedInstruction(value))),
  ]);
}

function normalizeOptionActivation(source) {
  const authoredType = clean(source?.type || source?.action);
  if (authoredType !== 'Click') return null;
  const authoredTarget = source.targetIdentity ?? source.target;
  const targetText = textFromTarget(authoredTarget);
  const matched = targetText.match(
    /^(?:(?:the\s+)?(?:first|second|third|fourth|fifth|\d+(?:st|nd|rd|th))\s+)?(.+?)\s+option\s*,\s*(.+)$/i,
  );
  if (!matched) return null;
  const ownerName = clean(matched[1]).replace(/^the\s+/i, '');
  const selectionText = clean(matched[2]);
  if (!ownerName || !selectionText) return null;
  const ownerTarget = isObject(authoredTarget)
    ? {
      ...clone(authoredTarget),
      kind: 'control',
      label: ownerName,
      accessibleName: ownerName,
      name: ownerName,
      role: null,
      controlType: clean(authoredTarget.controlType) || 'autocomplete',
    }
    : ownerName;
  return Object.freeze({
    authoredType,
    type: 'Select',
    targetIdentity: ownerTarget,
    selection: Object.freeze({ kind: 'exact_text', value: selectionText }),
    normalization: 'option_activation_to_select',
  });
}

function normalizeAction(source, context, findings) {
  const optionActivation = normalizeOptionActivation(source);
  // Prefer an explicit canonical type; fall back to inference from the
  // free-form action text before using the raw action string. This ensures
  // steps like 'Append "text" to field' resolve to 'Type', not a 50-char
  // sentence that fails VALID_STEP_TYPES validation.
  const explicitType = clean(source.type);
  // `source.action` sometimes holds a clean canonical type token (e.g.
  // "GoBack") that DISAGREES with a stale/wrong `source.type` (e.g.
  // "Click", left over from however the step was authored). When action
  // IS itself a valid step type, it's a stronger, deliberate signal than
  // type — trust it over a possibly-wrong type field.
  const actionAsCanonicalType = VALID_STEP_TYPES.includes(clean(source.action)) ? clean(source.action) : null;
  const inferredType = !explicitType ? inferCanonicalType(source.action) : null;
  const authoredType = optionActivation?.type || actionAsCanonicalType || explicitType || inferredType || clean(source.action);
  const type = authoredType;
  const path = `steps[${context.index}]`;
  if (!VALID_STEP_TYPES.includes(type)) {
    findings.push(finding(`${path}.type`, 'action_type_unsupported', 'Unsupported action type.', type));
  }
  const authoredId = clean(source.id || source.contractStepId || source.stepId || (source.order != null ? `step-${source.order}` : `step-${context.index + 1}`));
  const operationId = `action:${stableIdPart(context.caseId)}:${stableIdPart(authoredId)}`;
  const kind = type === 'WaitForState' ? OPERATION_KIND.SYNCHRONIZATION : OPERATION_KIND.ACTION;
  let explicitTarget = optionActivation?.targetIdentity ?? source.targetIdentity ?? source.target;
  if (NEVER_HAS_TARGET_ACTIONS.has(type)) {
    // These are pure navigation/whole-page controls with no UI element of
    // their own. Authored data can still carry a stale/descriptive
    // targetIdentity (e.g. a free-text label like "Navigate back to X
    // page.") left over from however the step was originally written —
    // that text isn't a real, resolvable element, and letting it through
    // makes downstream heuristics (e.g. "does the next step have a real
    // target") wrongly treat this operation as target-bearing, which then
    // leaks that bogus label into OTHER unrelated steps'/assertions'
    // narration and resolution.
    explicitTarget = null;
  }
  const targetRequired = !TARGET_OPTIONAL_ACTIONS.has(type);
  if (targetRequired && explicitTarget == null) {
    const fallbackLabel = clean(source.element || source.label || source.accessibleName || source.action) || 'Page element';
    explicitTarget = { label: fallbackLabel, accessibleName: fallbackLabel };
  }
  const targetIdentity = explicitTarget == null
    ? null
    : normalizeTargetIdentity(explicitTarget, `${path}.targetIdentity`, findings);
  const normalizedValue = normalizeValue(type, source, path, findings);
  const selection = type === 'Select'
    ? optionActivation?.selection || normalizeSelection(
        source.selectionCriteria ?? source.selection ?? source.value,
        `${path}.selection`,
        findings,
        { exactAuthoredValue: source.value },
      )
    : null;
  if (!optionActivation && type !== 'Select' && (source.selectionCriteria != null || source.selection != null)) {
    findings.push(finding(`${path}.selection`, 'selection_forbidden', 'Only Select accepts a selection contract.'));
  }

  return Object.freeze({
    schemaVersion: CONTRACT_VERSION,
    operationId,
    actionOccurrenceId: `occurrence:${operationId}:1`,
    kind,
    type,
    authoredType,
    normalization: optionActivation?.normalization || null,
    authoredCaseId: context.caseId,
    authoredStepId: authoredId || null,
    assertionId: null,
    ordinal: Number.isInteger(source.ordinal) ? source.ordinal : context.index + 1,
    targetIdentity,
    targetAliases: normalizeTargetAliases(source, targetIdentity),
    value: normalizedValue.value,
    valueRef: normalizedValue.valueRef,
    selection,
    condition: clone(source.condition || null),
    expected: clone(source.expected ?? null),
    destination: clone(
      source.destination
        || source.authoredDestination
        || source.operationCheck?.condition
        || source.operationCheck?.target
        || null,
    ),
    operationCheck: clone(source.operationCheck || null),
    dependencies: normalizeDependencies(source.dependsOn || source.dependencies),
    optional: source.optional === true
      || source.required === false
      || clean(source.condition?.onFalse).toLowerCase() === 'skip',
    required: source.required !== false,
    source: 'case_contract_v1',
  });
}

function normalizeAssertion(source, context, findings) {
  const explicitType = clean(source.type || source.assertionType);
  // Infer assertion type from free-form action text when no explicit type is set.
  // This handles steps like "Confirm the field is disabled" → AssertDisabled.
  const inferredAssertionType = !explicitType ? inferAssertionType(source.action) : null;
  const type = explicitType || inferredAssertionType || 'AssertText';
  const path = `assertions[${context.index}]`;
  if (!VALID_ASSERTION_TYPES.includes(type)) {
    findings.push(finding(`${path}.type`, 'assertion_type_unsupported', 'Unsupported assertion type.', type));
  }
  // For inline assertion-like steps, fall back to stepId, order, or index.
  const assertionId = clean(source.id || source.assertionId || source.contractStepId || source.stepId || (source.order != null ? `assertion-${source.order}` : `assertion-${context.index + 1}`));
  const operationId = `assertion:${stableIdPart(context.caseId)}:${stableIdPart(assertionId)}`;

  // Infer target from action text when no explicit target is provided.
  // Patterns: 'Confirm the "Field Name" field is X' → target = "Field Name"
  let target = source.targetIdentity ?? source.target;
  if (target == null && source.action) {
    const actionText = String(source.action);
    const targetMatch = actionText.match(/["']([^"']+)["']\s*(?:field|input|element|text\s*box|button|control)?/i);
    if (targetMatch) {
      target = { label: targetMatch[1], accessibleName: targetMatch[1] };
    }
  }
  const targetIdentity = target == null
    ? null
    : normalizeTargetIdentity(target, `${path}.targetIdentity`, findings);

  // Infer expected value from action text or source.value for assertion-like steps.
  // Pattern: 'value is "ortonikc"' or 'contains "This text is readonly"'
  let expected = clone(source.expected ?? null);
  if (expected == null && source.value) {
    expected = source.value;
  }
  if (expected == null && source.action) {
    const actionText = String(source.action);
    const expectedMatch = actionText.match(/(?:is|contains?|equals?|shows?)\s+["']([^"']+)["']/i);
    if (expectedMatch) {
      expected = expectedMatch[1];
    }
  }

  return Object.freeze({
    schemaVersion: CONTRACT_VERSION,
    operationId,
    actionOccurrenceId: `occurrence:${operationId}:1`,
    kind: OPERATION_KIND.ASSERTION,
    type,
    authoredCaseId: context.caseId,
    authoredStepId: clean(source.contractStepId) || null,
    assertionId: assertionId || null,
    sourceStepRef: clean(source.stepId) || null,
    ordinal: Number.isInteger(source.ordinal) ? source.ordinal : context.index + 1,
    targetIdentity,
    targetAliases: normalizeTargetAliases(source, targetIdentity),
    comparator: clean(source.comparator) || null,
    payload: clone(source.payload || null),
    verify: clone(source.verify || null),
    expected: clone(expected),
    dependencies: normalizeDependencies(source.dependsOn || source.dependencies),
    optional: false,
    required: source.required !== false,
    nonBlocking: true,
    source: 'case_contract_v1',
  });
}

function compileOperationContractV2(caseContract = {}) {
  const findings = [];
  const caseId = clean(caseContract.id || caseContract.caseId);
  if (!caseId) findings.push(finding('case.id', 'case_identity_required', 'Case requires a stable id.'));
  const steps = Array.isArray(caseContract.steps) ? caseContract.steps : [];
  const separateAssertions = Array.isArray(caseContract.assertions) ? caseContract.assertions : [];
  const inlineOperations = steps.map((source, index) => {
    const normalizedSource = isObject(source) ? source : {};
    // Route as assertion if the step has an explicit Assert* type, OR if the
    // action text is a confirmation/verification instruction ("Confirm the
    // value...", "Verify the field is disabled", etc.).
    const isAssertion = /^Assert/i.test(clean(normalizedSource.type))
      || (!clean(normalizedSource.type) && isAssertionLikeAction(normalizedSource.action));
    return isAssertion
      ? normalizeAssertion(normalizedSource, { caseId, index }, findings)
      : normalizeAction(normalizedSource, { caseId, index }, findings);
  });
  const additionalAssertions = separateAssertions.length
    ? separateAssertions.map((source, index) => normalizeAssertion(
      isObject(source) ? source : {},
      { caseId, index: steps.length + index },
      findings,
    ))
    : [];
  let previousOrderedOperationId = null;
  const operations = Object.freeze(
    [...inlineOperations, ...additionalAssertions].map((operation) => {
      // Authored order is not failure dependency. The scheduler waits for the
      // preceding operation to finish, but only explicit dependencies may
      // suppress a later operation after an execution error. This prevents a
      // transient resolver/evidence problem from cancelling the rest of a
      // long form while preserving strict one-at-a-time step order.
      const ordered = Object.freeze({
        ...operation,
        orderingPredecessor: previousOrderedOperationId,
      });
      previousOrderedOperationId = operation.operationId;
      return ordered;
    }),
  );
  const actions = Object.freeze(operations.filter((operation) => operation.kind !== OPERATION_KIND.ASSERTION));
  const assertions = Object.freeze(operations.filter((operation) => operation.kind === OPERATION_KIND.ASSERTION));

  const ids = [...actions, ...assertions].map((operation) => operation.operationId);
  const duplicateIds = ids.filter((id, index) => ids.indexOf(id) !== index);
  for (const id of new Set(duplicateIds)) {
    findings.push(finding('operations', 'operation_identity_duplicate', 'Operation identity must be unique.', id));
  }
  if (findings.length) {
    throw new OperationContractError('CaseContractV1 could not be compiled into safe browser operations.', findings);
  }

  return Object.freeze({
    schemaVersion: CONTRACT_VERSION,
    caseId,
    operations,
    actions,
    assertions,
  });
}

module.exports = {
  CONTRACT_VERSION,
  OPERATION_KIND,
  TARGET_OPTIONAL_ACTIONS,
  VALUE_ACTIONS,
  VALUE_REQUIRED_ACTIONS,
  VALUE_OPTIONAL_ACTIONS,
  OperationContractError,
  containsPollutedInstruction,
  normalizeOptionActivation,
  normalizeTargetIdentity,
  compileOperationContractV2,
};
